export const LANG = {
  ru: {
    title: 'Мой день', today: 'Сегодня', calendar: 'Календарь', stats: 'Статистика', habits: 'Привычки',
    addBlock: 'Добавить блок', addTask: 'Добавить задачу', addHabit: 'Добавить привычку',
    newBlock: 'Новый блок', newTask: 'Новая задача', newHabit: 'Новая привычка',
    done: 'Выполнено', failed: 'Провалено', routine: 'Рутина', routineHint: 'Повторяется каждый день',
    deleteBlock: 'Удалить блок', deleteTask: 'Удалить задачу',
    noTasks: 'Нет задач. Добавьте первую.', tasksOf: 'задач', blockColor: 'Цвет блока',
    cancel: 'Отмена', save: 'Сохранить', export: 'Экспорт', import: 'Импорт',
    dayProgress: 'Прогресс дня', weekProgress: 'Прогресс недели',
    monthProgress: 'Прогресс месяца', yearProgress: 'Прогресс года',
    newDay: 'Новый день! 🌅', newDayMsg: 'Рутинные задачи перенесены. Отличного дня!',
    startDay: 'Начать день 🚀',
    todayBadge: 'Сегодня', planningBadge: 'Планирование', historyBadge: 'История',
    days: ['Пн','Вт','Ср','Чт','Пт','Сб','Вс'],
    months: ['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'],
    monthsShort: ['Янв','Фев','Мар','Апр','Май','Июн','Июл','Авг','Сен','Окт','Ноя','Дек'],
    byBlock: 'По блокам (сегодня)', streak: 'дней подряд', habitsGrid: 'Сетка привычек',
    week: 'Нед.', month: 'Мес.', year: 'Год',
  },
  en: {
    title: 'My Day', today: 'Today', calendar: 'Calendar', stats: 'Stats', habits: 'Habits',
    addBlock: 'Add block', addTask: 'Add task', addHabit: 'Add habit',
    newBlock: 'New block', newTask: 'New task', newHabit: 'New habit',
    done: 'Done', failed: 'Failed', routine: 'Routine', routineHint: 'Repeats every day',
    deleteBlock: 'Delete block', deleteTask: 'Delete task',
    noTasks: 'No tasks yet. Add your first.', tasksOf: 'tasks', blockColor: 'Block color',
    cancel: 'Cancel', save: 'Save', export: 'Export', import: 'Import',
    dayProgress: 'Day progress', weekProgress: 'Week progress',
    monthProgress: 'Month progress', yearProgress: 'Year progress',
    newDay: 'New day! 🌅', newDayMsg: 'Routine tasks carried over. Have a great day!',
    startDay: 'Start day 🚀',
    todayBadge: 'Today', planningBadge: 'Planning', historyBadge: 'History',
    days: ['Mo','Tu','We','Th','Fr','Sa','Su'],
    months: ['January','February','March','April','May','June','July','August','September','October','November','December'],
    monthsShort: ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
    byBlock: 'By block (today)', streak: 'day streak', habitsGrid: 'Habit grid',
    week: 'Week', month: 'Month', year: 'Year',
  },
};
